version: '3'
services:
  db:
    image: 'postgres:14.7'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'app'
      POSTGRES_DB: 'app'
    volumes:
      - './dev/db/initdb:/docker-entrypoint-initdb.d'
  api:
    build: '.'
    depends_on:
      - db
    ports:
      - '8080:8080'
    volumes:
      - ./app:/app/app
    environment:
      MOISI_MATCHING_SYSTEM_DATABASE_URL: 'postgresql://db:5432?user=app&password=password'
    command: 'uvicorn main:app --host 0.0.0.0 --port 8080 --reload'
  web:
    image: 'nginx:latest'
    depends_on:
      - 'api'
    ports:
      - '8000:80'
      - '443:443'
    volumes:
      - ./dev/web/nginx-log:/var/log/nginx
      - ./dev/web/nginx/ssl:/etc/nginx/ssl
      - ./dev/web/html:/var/www/html
      - ./dev/web/nginx/conf.d:/etc/nginx/conf.d
