version: '3'
services:
  db:
    image: 'postgres:14.7'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'app'
      POSTGRES_DB: 'app'
    volumes:
      - './dev/db/initdb:/docker-entrypoint-initdb.d'
  # web:
  #   image: 'nginx:latest'
  #   depends_on:
  #     - 'api'
  #   ports:
  #     - '443:443'
  #   volumes:
  #     - ./dev/web/nginx-log:/var/log/nginx
  #     - ./dev/web/nginx/ssl:/etc/nginx/ssl
  #     - ./dev/web/html:/var/www/html
  #     - ./dev/web/nginx/conf.d:/etc/nginx/conf.d
  api:
    hostname: 'matching-system'
    ports:
      - '8080:8080'
    build: '.'
    environment:
      MOISI_MATCHING_SYSTEM_DATABASE_URL: 'postgresql://db:5432?user=app&password=password'
