"""add match entry link

Revision ID: d99908bef857
Revises: 8f41a2cce792
Create Date: 2023-04-20 13:17:04.845695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99908bef857'
down_revision = '8f41a2cce792'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_entry_links',
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.add_column('matches', sa.Column('committed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'committed_at')
    op.drop_table('match_entry_links')
    # ### end Alembic commands ###
